### ISSUE TITLE
Broke with iTunes 12.7 update

### ISSUE THREAD

**Issue by alexreg** [dotson/iDevice-Sync#1]
Any chance of a quick fix? :-)

**Comment by dotson** [comment]
Can you give it a couple more tries and let me know if it still isn't working? I thought it was broke this morning but after a little while it seems to be working just fine.

I'm going to poke at it this weekend and try to make it break just to be sure.

**Comment by alexreg** [comment]
Nope, definitely broke, sorry. Restarted, reconnected devices, and they're not showing up in Alfred.

**Comment by dotson** [comment]
Ok, thanks for checking! It's definitely working for me; I'll do some testing to recreate and fix.

**Comment by dotson** [comment]
Can you run the workflow with the debugging window open and copy/paste the All Information output here for me to look at?

Also, what version of MacOS and Alfred are you running? There is currently an Alfred 3.5 Pre-Release, build 871, that's the most bleeding edge version available.

Thanks!!

**Comment by alexreg** [comment]
Mac OS X 10.12.6
Alfred 3.4.1, Build 860

```
Starting debug for 'iDevice Sync'

[2017-09-16 22:55:33][ERROR: action.script] 854:921: execution error: System Events got an error: Can’t get window "iTunes" of process "iTunes". (-1728)
[2017-09-16 22:55:35][ERROR: action.script] 174:241: execution error: System Events got an error: Can’t get window "iTunes" of process "iTunes". (-1728)
```

**Comment by dotson** [comment]
Thanks! Try replacing your version with the beta uploaded below and let me know if it works. I think the function I've been using to watch for the sync to complete may finally be dead. Might need to remove that ability if I can't find another way to do it.

https://github.com/dotson/iDevice-Sync/blob/master/Versions/iDevice%20Sync%20v1.3.03b.alfredworkflow

**Comment by alexreg** [comment]
Funniest thing is, it just started randomly working for me again today! How very odd. The new beta works too though. :-)

**Comment by dotson** [comment]
That's definitely interesting, glad it's working! I'll probably clean up this beta and release it later tonight; this workflow was overdue for a bit of a clean shave anyway. 

Thanks!

**Comment by alexreg** [comment]
Great. That should help it be more robust for the future at least. Thanks for the speedy responses!

**Comment by dotson** [comment]
Happy to help, thanks for letting me know it wasn't working for you!

Fully pushed 1.3.03 to fix this issue and clean up the completion-watcher code. Closing this issue for now, please let me know if there are any other problems.

**Comment by alexreg** [comment]
I'm afraid it's broken again... at least, on my system. Are you experiencing this too?

**Comment by dotson** [comment]
Thanks for letting me know, @alexreg. It seems to work fine for me; I use it daily at least. Here's the versions I'm running, which I think are all current:
- iTunes 12.7.2.58
- Alfred 3.5.1
- iDevice Sync 1.3.03

I haven't made any changes since the last update. Have you installed anything new that might be a conflict?

I can poke around and try to force errors to see if I can help. If you don't mind, can you run the workflow with the debugging window open and copy/paste the 'All Information' output here for me to look at? That was very helpful last time.

**Comment by alexreg** [comment]
You knows what... I just reinstalled the latest version, and hey presto. I forgot to copy the error in the debug pane before that, but something about a missing file "Working Data". So it looks like the installation of the workflow got corrupted somehow. Presumably during an upgrade of Alfred, or something I inadvertently did on the system.

Sorry for troubling you, anyway.

**Comment by dotson** [comment]
No problem at all, thanks for following up and letting me know it's working for you again!
