### ISSUE TITLE
Catalina compatibility

### ISSUE THREAD

**Issue by dotson** [dotson/iDevice-Sync#3]
There is currently no apple script solution to syncing devices on Catalina. Monitoring is ongoing for potential solution that doesn't involve GUI scripting

**Comment by alexreg** [comment]
Hello. Any update on this yet? Still no luck, I suppose?

**Comment by dotson** [comment]
Hi! Someone [came up with a script](https://apple.stackexchange.com/questions/372415/using-applescript-to-sync-iphone-in-catalina) that claims to work on Big Sur, but I haven't tested it. 

Unfortunately, it requires GUI scripting which makes it very prone to breaking across all other/future OSes if Apple makes even the slightest change to the Finder window. It also requires the user to input all the names of their devices in advance rather than just looking for any device and then outputting the names in Alfred. 

Both of those things potentially make this much more effort to set up and to maintain over time. I can spend a little time trying it out and see if it seems helpful, but it's nowhere near as elegant and long term of a solution compared to the original workflow's intention.

**Comment by alexreg** [comment]
Thanks for the update. Indeed, GUI scripting isn't nearly as nice a solution. A shame that Apple hasn't made this easy...

**Comment by dotson** [comment]
I just pushed a 2.0 update that uses the GUI scripting. It isn't perfect but it works and is less ugly to use than I expected. I also didn't like having this workflow hanging out there without any kind of update. 

This version requires you to enter in the names of your devices in the variable window for the workflow ([screenshot](https://github.com/dotson/iDevice-Sync/blob/master/Screenshots/2.0%20Update.png)). If you get a new device or rename an existing one, the workflow won't know that unless you tell it. I'm assuming that for most folks this is generally an infrequent use case so it should be generally set and forget.

Thanks for the reminder on this, I'm glad to have this back up and working again.

**Comment by alexreg** [comment]
Thanks very much! I'll give it a go.
